kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: golang:1.16
    commands:
      - go vet ./...
      - go test -v -coverprofile=coverage.txt -covermode=atomic ./...
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov-token
      files:
        - coverage.txt
